### ISSUE TITLE
Friction when adding URL shortcut

### ISSUE THREAD

**Issue by andreking** [issmirnov/zap#2]
The process to add a shortcut for a URL is currently:
(1) Edit /etc/hosts
(2) Edit /usr/local/etc/zap/c.yml
(3) sudo brew services restart zap

Consider developing 1-step process for adding a shortcut. Ideally, this should be as easy as adding the mapping of shortcut => URL to a config file and hitting save.

**Comment by issmirnov** [comment]
Great idea, thanks!

Notes to future me:
- add polling option to zap to detect if local config file is out of sync, reload when it happens. set up some reasonable interval, 15-60 seconds ideally. This solves hot reloading.
- Add `-write-hosts` option that is stored as option in app config. If zap is running with RW privileges on `/etc/hosts` we can flush top level shortcuts into it. This would have to be a flag added in the homebrew install for the service file.

**Comment by issmirnov** [comment]
Hey,

You can install the latest version by running `brew install issmirnov/apps/zap` and then `sudo brew services restart zap`

After that, any changes to `/usr/local/etc/zap/c.yml` will be automatically picked up by zap, as well as written to `/etc/hosts`, no restarts or manual editing required.

Thanks for a great suggestion!
